installCRDs: true
# values.yaml
validatingWebhookConfigurationAnnotations:
  cert-manager.io/inject-ca-from-secret: test-cert-manager/cert-manager-01-webhook-ca

validatingWebhookConfigurationNamespaceSelector:
  matchExpressions:
    - key: cert-manager.io/disable-validation
      operator: NotIn
      values:
        - 'true'
    - key: control-plane
      operator: NotIn
      values:
        - 'true'
    - key: kubernetes.azure.com/managedby
      operator: NotIn
      values:
        - aks


